/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/zNCE7BfocWp
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { JSX, SVGProps } from "react";

function BettingCard({
  title,
  description,
  yesVotes,
  noVotes,
  id,
}: {
  title: string;
  description: string;
  yesVotes: number;
  noVotes: number;
  id: number;
}) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>{title}</CardTitle>
        <CardDescription>{description}</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <ThumbsUpIcon className="h-5 w-5 text-green-500" />
            <span className="text-lg font-medium">{yesVotes}</span>
            <span className="text-gray-500">Yes</span>
          </div>
          <div className="flex items-center gap-2">
            <ThumbsDownIcon className="h-5 w-5 text-red-500" />
            <span className="text-lg font-medium">{noVotes}</span>
            <span className="text-gray-500">No</span>
          </div>
        </div>
      </CardContent>
      <CardFooter>
        <Button>
          <Link href={`/details/${id}`}>Join Market</Link>
        </Button>
      </CardFooter>
    </Card>
  );
}

export default function Landing() {
  const bettingData = [
    {
      title: "Will Elon Musk step down as Twitter CEO?",
      description:
        "Bet on whether Elon Musk will step down as Twitter CEO by the end of 2023.",
      yesVotes: 2345,
      noVotes: 1234,
    },
    {
      title: "Will the S&P 500 reach a new all-time high in 2024?",
      description:
        "Bet on whether the S&P 500 will reach a new all-time high by the end of 2024.",
      yesVotes: 4567,
      noVotes: 2890,
    },
    {
      title: "Will the US enter a recession in 2023?",
      description:
        "Bet on whether the US economy will enter a recession in 2023.",
      yesVotes: 7890,
      noVotes: 3456,
    },
  ];
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1 py-12 px-6 md:px-12 lg:px-24">
        <div className="max-w-5xl mx-auto">
            <h1 className="text-3xl font-bold mb-8">Active Prediction Markets</h1>
            <div className="grid gap-6 grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
            {bettingData.map((bet, index) => (
                <BettingCard
                key={index}
                id={index}
                title={bet.title}
                description={bet.description}
                yesVotes={bet.yesVotes}
                noVotes={bet.noVotes}
                />
            ))}
            </div>
        </div>
        </main>
    </div>
  );
}

function BarChartIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="20" y2="10" />
      <line x1="18" x2="18" y1="20" y2="4" />
      <line x1="6" x2="6" y1="20" y2="16" />
    </svg>
  );
}

function ThumbsDownIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 14V2" />
      <path d="M9 18.12 10 14H4.17a2 2 0 0 1-1.92-2.56l2.33-8A2 2 0 0 1 6.5 2H20a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.76a2 2 0 0 0-1.79 1.11L12 22h0a3.13 3.13 0 0 1-3-3.88Z" />
    </svg>
  );
}

function ThumbsUpIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 10v12" />
      <path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>
  );
}
