/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HHdI4g3EZuz
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { PlacebetPopup } from "@/components/placebetPopup";
import { Button } from "@/components/ui/button";
import {
  CardTitle,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import { JSX, SVGProps } from "react";
import {DialogTrigger} from "@radix-ui/react-dialog";

export default function Details() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1 py-12 px-6 md:px-12 lg:px-24">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-bold mb-8">
            Will Elon Musk step down as Twitter CEO?
          </h1>
          <Card>
            <CardHeader>
              <CardTitle>
                Bet on whether Elon Musk will step down as Twitter CEO by the
                end of 2023.
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <ThumbsUpIcon className="h-5 w-5 text-green-500" />
                  <span className="text-lg font-medium">2,345</span>
                  <span className="text-gray-500">Yes</span>
                </div>
                <div className="flex items-center gap-2">
                  <ThumbsDownIcon className="h-5 w-5 text-red-500" />
                  <span className="text-lg font-medium">1,234</span>
                  <span className="text-gray-500">No</span>
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <div className="grid grid-cols-2 gap-4">
                <PlacebetPopup>
                  <Button>Bet Yes</Button>
                </PlacebetPopup>
                <PlacebetPopup>
                  <Button variant="outline">Bet No</Button>
                </PlacebetPopup>
              </div>
            </CardFooter>
          </Card>
          <div className="mt-8">
            <h2 className="text-2xl font-bold mb-4">Bet Details</h2>
            <Card>
              <CardContent>
                <div className="grid grid-cols-2 gap-4">
                  <div className="mt-4">
                    <h3 className="text-lg font-bold mb-2">Bet Amount</h3>
                    <div className="flex items-center gap-2">
                      <BitcoinIcon className="h-6 w-6 text-gray-500" />
                      <span className="text-2xl font-bold">0.1 ETH</span>
                    </div>
                  </div>
                  <div className="mt-4">
                    <h3 className="text-lg font-bold mb-2">Potential Payout</h3>
                    <div className="flex items-center gap-2">
                      <BitcoinIcon className="h-6 w-6 text-gray-500" />
                      <span className="text-2xl font-bold">0.5 ETH</span>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
          <div className="mt-8">
            <h2 className="text-2xl font-bold mb-4">Market Details</h2>
            <Card>
              <CardContent>
                <div className="grid grid-cols-2 gap-4">
                  <div className="mt-4">
                    <h3 className="text-lg font-bold mb-2">Market Creator</h3>
                    <div className="flex items-center gap-2">
                      <Avatar>
                        <AvatarImage
                          alt="@creator"
                          src="/placeholder-avatar.jpg"
                        />
                        <AvatarFallback>CR</AvatarFallback>
                      </Avatar>
                      <span>@creator</span>
                    </div>
                  </div>
                  <div className="mt-4">
                    <h3 className="text-lg font-bold mb-2">Market End Date</h3>
                    <div className="flex items-center gap-2">
                      <CalendarDaysIcon className="h-6 w-6 text-gray-500" />
                      <span>December 31, 2023</span>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  );
}

function BitcoinIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M11.767 19.089c4.924.868 6.14-6.025 1.216-6.894m-1.216 6.894L5.86 18.047m5.908 1.042-.347 1.97m1.563-8.864c4.924.869 6.14-6.025 1.215-6.893m-1.215 6.893-3.94-.694m5.155-6.2L8.29 4.26m5.908 1.042.348-1.97M7.48 20.364l3.126-17.727" />
    </svg>
  );
}

function CalendarDaysIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
      <path d="M8 14h.01" />
      <path d="M12 14h.01" />
      <path d="M16 14h.01" />
      <path d="M8 18h.01" />
      <path d="M12 18h.01" />
      <path d="M16 18h.01" />
    </svg>
  );
}

function ThumbsDownIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 14V2" />
      <path d="M9 18.12 10 14H4.17a2 2 0 0 1-1.92-2.56l2.33-8A2 2 0 0 1 6.5 2H20a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.76a2 2 0 0 0-1.79 1.11L12 22h0a3.13 3.13 0 0 1-3-3.88Z" />
    </svg>
  );
}

function ThumbsUpIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 10v12" />
      <path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>
  );
}
